### ISSUE TITLE
Update to 1.21.4 Please

### ISSUE THREAD

**Issue by ghost** [ShayBox/Durability101#17]

**Comment by ShayBox** [comment]
Fabric 1.21 builds have been published, forge has not yet updated.

**Comment by venaminecraft** [comment]
Thanks 😊

**Comment by venaminecraft** [comment]
Tested latest 1.21.3 build on 1.21.4.

java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_2378.method_40264(net.minecraft.class_5321)'
at knot//net.minecraft.class_332.renderDurability101(class_332.java:1792)
at knot//net.minecraft.class_332.handler$zjf000$durability101$drawItemInSlot(class_332.java:1782)
at knot//net.minecraft.class_332.method_51432(class_332.java:535)
at knot//net.minecraft.class_332.method_51431(class_332.java:523)
at knot//net.minecraft.class_329.method_1762(class_329.java:1314)
at knot//net.minecraft.class_329.method_1759(class_329.java:598)
at knot//net.minecraft.class_329.method_55805(class_329.java:543)
at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
at knot//net.minecraft.class_9080.method_55812(class_9080.java:22)
at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
at knot//net.minecraft.class_9080.method_55809(class_9080.java:29)
at knot//net.minecraft.class_329.method_1753(class_329.java:234)
at knot//net.minecraft.class_757.method_3192(class_757.java:533)
at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
at knot//net.minecraft.class_310.method_1514(class_310.java:922)
at knot//net.minecraft.client.main.Main.main(Main.java:267)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by venaminecraft** [comment]
Thanks 😊
